CREATE TABLE test_table (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    val TEXT DEFAULT "",
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
)
CHARACTER SET = "utf8mb4",
COLLATE = 'utf8mb4_unicode_ci',
ENGINE = InnoDB,
ROW_FORMAT = DYNAMIC;
