CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age TINYINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS groups (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_groups (
    user_id BIGINT UNSIGNED NOT NULL,
    group_id INT UNSIGNED NOT NULL,

    PRIMARY KEY(user_id, group_id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_group_id FOREIGN KEY (group_id) REFERENCES groups (id)
);
