version: '3'

x-TZ: &TZ "Asia/Tokyo"

services:
  mariadb:
    image: mariadb:10.6.4
    restart: always
    volumes:
      - db-store:/var/lib/mysql
    environment:
      TZ: *TZ
      MARIADB_DATABASE: &MARIADB_DATABASE app_db
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_USER: &MARIADB_USER app
      MARIADB_PASSWORD: &MARIADB_PASSWORD app
  web:
    build:
      context: .
    command: /go/out/app
    ports:
      - "8080:80"
    volumes:
      - ./:/opt/app
      - ~/.gitconfig:/home/app/.gitconfig
      - ~/.ssh:/home/app/.ssh:ro
    links:
      - "mariadb:db"
    environment:
      TZ: *TZ
      DB_USER: *MARIADB_USER
      DB_PASSWORD: *MARIADB_PASSWORD
      DB_NAME: *MARIADB_DATABASE
      DB_HOST: "db"

volumes:
  db-store:
