// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Groups     string
	TestTable  string
	UserGroups string
	Users      string
}{
	Groups:     "groups",
	TestTable:  "test_table",
	UserGroups: "user_groups",
	Users:      "users",
}
